#!/bin/bash

# args: [blob-name]

set -e
set -u

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "" == "${1:-}" ] ; then
  for BLOB_NAME in $( find "$DIR" -type d -depth 1 | cut -c3- | xargs basename ) ; do
    echo "==> $BLOB_NAME"

    $DIR/upgrade "$BLOB_NAME"
  done

  exit
elif [ ! -d "$DIR/$1" ] ; then
  echo "$1 is not configured for updates"

  exit 1
fi

export BLOB_NAME="$1"

SRC_DIR="$DIR/$BLOB_NAME"
BLOB_DIR="$DIR/../../blobs/$BLOB_NAME"

if [ -f "$SRC_DIR/VERSION" ] ; then
  VERSION_LOCAL=$( cat "$SRC_DIR/VERSION" )
else
  VERSION_LOCAL=missing
fi

echo "--| local $VERSION_LOCAL"

VERSION_CHECK=$( . "$SRC_DIR/check" )

echo "--| check $VERSION_CHECK"

if [[ "$VERSION_CHECK" == "$VERSION_LOCAL" ]] ; then
  exit
fi

echo "--> fetching new version"

rm -fr "$BLOB_DIR-new"
mkdir -p "$BLOB_DIR-new"

cd "$BLOB_DIR-new"

export VERSION="$VERSION_CHECK"
"$SRC_DIR/get"

rm -fr "$BLOB_DIR"
mv "$BLOB_DIR-new" "$BLOB_DIR"

echo "$VERSION" > "$SRC_DIR/VERSION"

echo "-->" $( du -sh $BLOB_DIR | cut -f1 )
