#!/bin/bash

set -eu -o pipefail

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/.."

hugo_version=0.62.1
hugo="${dir}/tmp/hugo-${hugo_version}/hugo"

if [[ ! -e "$hugo" ]]; then
  hugo_download_suffix=""

  if [[ "$OSTYPE" == "linux-gnu" ]]; then
    hugo_download_suffix="linux-64bit"
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    hugo_download_suffix="macOS-64bit"
  else
    echo "$0: warning: unable to detect platform for downloading hugo"
  fi

  if [[ -n "$hugo_download_suffix" ]]; then
    echo "downloading hugo (v${hugo_version})"

    mkdir -p "$( dirname "$hugo" )"
    wget -qO- "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_${hugo_download_suffix}.tar.gz" \
     | tar -xzf- -C "$( dirname "$hugo" )" hugo
  fi
fi

baseurl="http://127.0.0.1:1313"

if which gp >/dev/null 2>&1 ; then
  baseurl="$( gp url 1313 )"
fi

exec "$hugo" serve --baseURL "$baseurl" --bind 0.0.0.0 -p 1313 --appendPort=false
